version: "3.9"

services:
  cassandra:
    image: cassandra:latest
    container_name: my-cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=MPGCluster
      - CASSANDRA_SEEDS=my-cassandra
      - MAX_HEAP_SIZE=5G
      - HEAP_NEWSIZE=800M
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "SELECT now() FROM system.local"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
    restart: unless-stopped
    networks:
      - "backend"

  cassandra-init:
    image: cassandra:latest
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - backend
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo 'Creating keyspace...'
        cqlsh my-cassandra -e "CREATE KEYSPACE IF NOT EXISTS mpg_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};"

        echo 'Creating table mpg_keyspace.exhibits...'
        cqlsh my-cassandra -e "CREATE TABLE IF NOT EXISTS mpg_keyspace.exhibits (id uuid PRIMARY KEY, descriptor blob, image blob, height int, width int, title text, description text);"

  server:
    build: .
    expose:
      - 8888
    ports:
      - "8888:8888"
    networks:
      - backend
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs

volumes:
  cassandra_data:

networks:
  backend:
    name: backend
